CHECKPOINT;
GO
DBCC DROPCLEANBUFFERS
GO
DBCC FREEPROCCACHE
GO
DBCC FREESESSIONCACHE
GO
DBCC FREESYSTEMCACHE ( 'ALL')
GO
DBCC SHRINKFILE ([tempdev2], EMPTYFILE);
GO
ALTER DATABASE [tempdb]  REMOVE FILE [tempdev2]
GO
