USE TempDB
GO

SELECT		DS.name AS filegroup_name
		, DF.file_id
		, DF.name AS logical_name
		, DF.physical_name AS physical_name
		, DF.type_desc AS file_type_desc
		, CASE DF.is_percent_growth
				WHEN 0 THEN CASE DF.growth WHEN 0 THEN 'DISABLED' ELSE CAST(DF.growth / 128 AS varchar(20)) + ' MB' END
				ELSE CAST(DF.growth AS varchar(3)) + ' %'
		END AS growth
		, CAST(DF.size / 128.0 AS decimal(14, 2)) AS file_size_MB
		, CAST(FILEPROPERTY(DF.name, 'SpaceUsed') / 128.0 AS decimal(14, 2)) AS occupied_size_MB
		, CASE DF.max_size
			WHEN -1 THEN 'UNLIMITED'
			WHEN 0 THEN 'DISABLED'
			ELSE CAST(CAST(DF.max_size / 128.0 AS bigint) AS varchar(20)) 
		END AS max_size_MB
FROM		sys.database_files AS DF
LEFT JOIN	sys.data_spaces AS DS
			ON DF.data_space_id = DS.data_space_id
ORDER BY	DF.type_desc DESC, DF.file_id

/*
CHECKPOINT;
GO
DBCC DROPCLEANBUFFERS;
GO
DBCC FREEPROCCACHE;
GO
--DBCC FREESYSTEMCACHE ('ALL', [default]) WITH MARK_IN_USE_FOR_REMOVAL;
--DBCC FREESYSTEMCACHE ('ALL', internal) WITH MARK_IN_USE_FOR_REMOVAL;
DBCC FREESYSTEMCACHE ('ALL') WITH MARK_IN_USE_FOR_REMOVAL;
DBCC FREESESSIONCACHE;
GO

CHECKPOINT
GO

DBCC SHRINKFILE (tempdev, EMPTYFILE);   --- New file size in MB
DBCC SHRINKFILE (temp2, EMPTYFILE);   --- New file size in MB
DBCC SHRINKFILE (temp3, EMPTYFILE);   --- New file size in MB
DBCC SHRINKFILE (temp4, EMPTYFILE);   --- New file size in MB

-- ALTER DATABASE TempDB REMOVE FILE temp4
*/

--USE TempDB; CHECKPOINT; DBCC SHRINKFILE (templog, 0); ALTER DATABASE TempDB MODIFY FILE(NAME = templog, SIZE = 1GB, FILEGROWTH = 1GB)

/*
ALTER DATABASE TempDB MODIFY FILE (NAME = 'tempdev', SIZE = 1GB, MAXSIZE = 10GB, FILEGROWTH = 1GB)
ALTER DATABASE TempDB MODIFY FILE (NAME = 'tempdev2', SIZE = 1GB, MAXSIZE = 10GB, FILEGROWTH = 1GB)
ALTER DATABASE TempDB MODIFY FILE (NAME = 'tempdev3', SIZE = 1GB, MAXSIZE = 10GB, FILEGROWTH = 1GB)
ALTER DATABASE TempDB MODIFY FILE (NAME = 'tempdev4', SIZE = 1GB, MAXSIZE = 10GB, FILEGROWTH = 1GB)

ALTER DATABASE TempDB MODIFY FILE (NAME = 'tempdev', FILENAME = 'S:\SQL2017\MSSQL14.SQL2017\MSSQL\DATA\tempdb.mdf')
ALTER DATABASE TempDB MODIFY FILE (NAME = 'temp2', FILENAME = 'S:\SQL2017\MSSQL14.SQL2017\MSSQL\DATA\temp2.ndf')
ALTER DATABASE TempDB MODIFY FILE (NAME = 'temp3', FILENAME = 'S:\SQL2017\MSSQL14.SQL2017\MSSQL\DATA\temp3.ndf')
ALTER DATABASE TempDB MODIFY FILE (NAME = 'temp4', FILENAME = 'S:\SQL2017\MSSQL14.SQL2017\MSSQL\DATA\temp4.ndf')
ALTER DATABASE TempDB MODIFY FILE (NAME = 'templog', FILENAME = 'S:\SQL2017\MSSQL14.SQL2017\MSSQL\DATA\templog.ldf')
*/