SELECT	'BACKUP DATABASE ' + name
	+ ' TO DISK = ''\\BHBACKUP\SQL\BHWSUS\' + name + '_'
	+ REPLACE(CAST(CAST(GETDATE() AS date) AS char(10)), '-', '') + '.bak'' WITH COMPRESSION, CHECKSUM, INIT, STATS = 1'
FROM	sys.databases
WHERE	name NOT IN ('tempDB')


/*
BACKUP DATABASE BHDBA TO DISK = '\\BHBACKUP\SQL\BHWSUS\BHDBA_20150203.bak' WITH CHECKSUM, INIT, STATS = 1
BACKUP DATABASE master TO DISK = '\\BHBACKUP\SQL\BHWSUS\master_20150203.bak' WITH CHECKSUM, INIT, STATS = 1
BACKUP DATABASE model TO DISK = '\\BHBACKUP\SQL\BHWSUS\model_20150203.bak' WITH CHECKSUM, INIT, STATS = 1
BACKUP DATABASE msdb TO DISK = '\\BHBACKUP\SQL\BHWSUS\msdb_20150203.bak' WITH CHECKSUM, INIT, STATS = 1
BACKUP DATABASE SUSDB TO DISK = '\\BHBACKUP\SQL\BHWSUS\SUSDB_20150203.bak' WITH CHECKSUM, INIT, STATS = 1
*/